In [1]:
import numpy as np

In [4]:
list1 = [1, 2, 3]
print('list1:', list1)
print('list1 type:', type(list1))

array1 = np.array(list1)
print('array1:', array1)
print('array1 type:', type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


In [5]:
arrray1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array shape:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array shape:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array shape:', array3.shape)

print('array1:{:0}차원, array2:{:1}차원, arr3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array shape: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array shape: (1, 3)
array1:1차원, array2:2차원, arr3: 2차원


In [6]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

list2 = [1, 2, 'test']
array2 = np.array(list2) # 정수가 문자열로 변경됨
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3) # 정수가 실수로 변경됨
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64


- astype() 을 통한 타입 변환

In [2]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [8]:
# ndarray에서 axis 기반 연산함수
# axis = 0 (행 방향축), axis = 1 (열 방향축)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print(array2.sum())
print(array2.sum(axis=0)) # 행방향
print(array2.sum(axis=1)) # 열방향

15
[3 5 7]
[6 9]


In [9]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

# 변환할 수 없는 shape 구조를 입력하면 오류.
array1.reshape(4,3)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)
array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

In [10]:
array1 = np.arange(10)
print(array1)

# column axis 크기는 5에 고정하고, row axis 크기를 이에 맞춰 자동 변환 (2x5)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
print('array2:\n', array2)

# column axis 크기는 자동 변환, row axis 크기는 5에 고정 (5x2)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)
print('array3:\n', array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환, column axis = 1
array2d_1 = array1.reshape(-1, 1)
print('array2d_1 shape:', array2d_1.shape)
print('array2d_1:\n', array2d_1)

# 2차원 ndarray를 1차원으로 변환.
array1d = array2d_1.reshape(-1,)
print('array1d shape:', array1d.shape)
print('array1d:\n', array1d)

# 변환 불가능한 형태로 변경 시 오류.
array1 = np.arange(10)  
array4 = array1.reshape(-1, 4)

# -1값은 1개 인자에만 입력 가능.
array1.reshape(-1,-1)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]


ValueError: cannot reshape array of size 10 into shape (4)

In [12]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두번째 값:', array1[-2])

array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,cal=0) index:', array2d[0,0])
print('(row=0,cal=1) index:', array2d[0,1])
print('(row=1,cal=0) index:', array2d[1,0])
print('(row=2,cal=2) index:', array2d[2,2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,cal=0) index: 1
(row=0,cal=1) index: 2
(row=1,cal=0) index: 4
(row=2,cal=2) index: 9


In [13]:
# slicing
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

array4 = array1[:3]
print('array4')

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('arrary2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>
array4
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
arrary2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [14]:
# boolean indexing
array1d = np.arange(start=1, stop=10)
print(array1d)

print(array1d > 5)

var1 = array1d > 5
print('var1:', var1)
print(type(var1))

# [] 안에 array1d > 5 boolean indexing 적용.
print(array1d)
array3 = array1d[array1d > 5]
print('array1d >5 boolean indexing result:', array3)
print(type(array3))

boolean_indexes = np.array([False, False, False, False, True, True, True, True, False])
array3 = array1d[boolean_indexes]
print('boolean indexing result:', array3)

array1d = np.arange(start=1, stop=10)
target=[]

for i in range(0, 9):
  if array1d[i] > 5:
    target.append(array1d[i])
array_selected = np.array(target)
print(array_selected)

print(array1d[array1 > 5])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
array1d >5 boolean indexing result: [6 7 8 9]
<class 'numpy.ndarray'>
boolean indexing result: [5 6 7 8]
[6 7 8 9]
[6 7 8 9]


In [15]:
# sort(), argsort()

org_array = np.array([3,1,9,5])
print('origin matrix:', org_array)

#np.sort()
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환:', sort_array1)
print('np.sort() 호출 후 원본:', org_array)

#ndarray.sort() 
sort_array2 = org_array.sort()
org_array.sort()
print('org_array.sort() 호출 후 반환:', sort_array2)
print('org_array.sort() 호출 후 원본:', org_array)

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순:', sort_array1_desc)

array2d = np.array([[8, 12], 
                   [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('row sort:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('column sort:\n', sort_array2d_axis1)

org_array = np.array([3,1,9,5])
print(np.array(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 index:', sort_indices)

org_array = np.array([3,1,9,5])
print(np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78,95,84,98,88])

#score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스 반환
sort_indices = np.argsort(score_array)
print('sort indices:', sort_indices)

name_array_sort = name_array[sort_indices]

score_array_sort = score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)

origin matrix: [3 1 9 5]
np.sort() 호출 후 반환: [1 3 5 9]
np.sort() 호출 후 원본: [3 1 9 5]
org_array.sort() 호출 후 반환: None
org_array.sort() 호출 후 원본: [1 3 5 9]
내림차순: [9 5 3 1]
row sort:
 [[ 7  1]
 [ 8 12]]
column sort:
 [[ 8 12]
 [ 1  7]]
[3 1 9 5]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 index: [1 0 3 2]
[9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
sort indices: [0 2 4 1 3]
['john' 'sarah' 'samuel' 'mike' 'kate']
[78 84 88 95 98]


In [16]:
# 행렬 내적
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(a, b)
print('행렬 내적 결과:\n', dot_product)

a = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(a)
print('a의 전치 행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
a의 전치 행렬:
 [[1 3]
 [2 4]]
