In [1]:
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader

In [3]:
from matplotlib.pyplot import imshow
%matplotlib inline

In [9]:
trans = transforms.Compose([
    transforms.Resize((64, 128))
])
train_data = torchvision.datasets.ImageFolder(root='taco_and_burrito/train',
                                             transform=trans)

In [54]:
trans = transforms.Compose([
    transforms.Resize((64, 128))
])
test_data = torchvision.datasets.ImageFolder(root='taco_and_burrito/test',
                                            transform=trans)

In [56]:
for num, value in enumerate(test_data):
    data, label = value
    #print(num, data, label)

    if (label == 0):
        data.save('taco_and_burrito/test_resize/taco/%d_%d.jpg' %(num, label))
    else:
        data.save('taco_and_burrito/test_resize/burrito/%d_%d.jpg' %(num, label))

In [15]:
for num, value in enumerate(train_data):
    data, label = value
    print(num, data, label)
    
    if (label == 0):
        data.save('taco_and_burrito/train_resize/taco/%d_%d.jpg' %(num, label))
    else:
        data.save('taco_and_burrito/train_resize/burrito/%d_%d.jpg' %(num, label))

0 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2610> 0
1 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2CD0> 0
2 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566410> 0
3 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2BD0> 0
4 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566710> 0
5 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D25D0> 0
6 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566410> 0
7 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566B90> 0
8 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94534850> 0
9 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566710> 0
10 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95496750> 0
11 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81150> 0
12 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F944D2450> 0
13 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95459ED0> 0
14 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94

181 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95459D90> 0
182 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81BD0> 0
183 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D8A7D0> 0
184 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94524A10> 0
185 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81BD0> 0
186 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433390> 0
187 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95459ED0> 0
188 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433610> 0
189 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81D50> 0
190 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433250> 0
191 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D25D0> 0
192 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433710> 0
193 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566790> 0
194 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433390> 0
195 <PIL.Image.Image image mode=RG

303 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95496ED0> 0
304 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F9456E710> 0
305 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95459ED0> 0
306 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94524A10> 0
307 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94534150> 0
308 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D25D0> 0
309 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2610> 0
310 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2CD0> 0
311 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566790> 0
312 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2BD0> 0
313 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2CD0> 0
314 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566B90> 0
315 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D8A7D0> 0
316 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2610> 0
317 <PIL.Image.Image image mode=RG

432 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94534850> 1
433 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433390> 1
434 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95496250> 1
435 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95496750> 1
436 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F9456E710> 1
437 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81BD0> 1
438 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94524A10> 1
439 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2610> 1
440 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566410> 1
441 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F9451D750> 1
442 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566A50> 1
443 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81D50> 1
444 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566A50> 1
445 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95496ED0> 1
446 <PIL.Image.Image image mode=RG

560 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81150> 1
561 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566410> 1
562 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433390> 1
563 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95496750> 1
564 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566410> 1
565 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95459ED0> 1
566 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2CD0> 1
567 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566790> 1
568 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433610> 1
569 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95496ED0> 1
570 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F9452D510> 1
571 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F9452D110> 1
572 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F9452D290> 1
573 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D25D0> 1
574 <PIL.Image.Image image mode=RG

687 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94534150> 1
688 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D8AB90> 1
689 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81150> 1
690 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94524A10> 1
691 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81D50> 1
692 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94566710> 1
693 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433390> 1
694 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95496250> 1
695 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F95433710> 1
696 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D8A7D0> 1
697 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D8AB90> 1
698 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F954D2610> 1
699 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F94D81150> 1
700 <PIL.Image.Image image mode=RGB size=128x64 at 0x7F0F9452D910> 1
701 <PIL.Image.Image image mode=RG

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim
from torch.utils.data import DataLoader

import torchvision
import torchvision.transforms as transforms

In [19]:
device = 'cpu'
torch.manual_seed(777)

In [21]:
trans = transforms.Compose([
    transforms.ToTensor()
])
train_data = torchvision.datasets.ImageFolder(root='taco_and_burrito/train_resize',
                                             transform=trans)

In [22]:
data_loader = DataLoader(
    dataset=train_data, batch_size=8, shuffle=True, num_workers=2)

In [69]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(3, 6, 5),
            nn.ReLU(),
            nn.MaxPool2d(2),)
        self.layer2 = nn.Sequential(
            nn.Conv2d(6, 16, 5),
            nn.ReLU(),
            nn.MaxPool2d(2),)
        self.layer3 = nn.Sequential(
            nn.Linear(16*13*29, 120),
            nn.ReLU(),
            nn.Linear(120, 2))
    
    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.shape[0], -1)
        out = self.layer3(out)
        return out

In [70]:
# testing
net = CNN().to(device)
test_input = (torch.Tensor(3, 3, 64, 128)).to(device)
test_out = net(test_input)

In [71]:
net = CNN().to(device)

In [72]:
optimizer = optim.Adam(net.parameters(), lr=0.001)
loss_func = nn.CrossEntropyLoss().to(device)

In [73]:
total_batch = len(data_loader)

epochs = 20
for epoch in range(epochs):
    avg_cost = 0.0
    for num, data in enumerate(data_loader):
        imgs, labels = data
        imgs = imgs.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        out = net(imgs)
        loss = loss_func(out, labels)
        loss.backward()
        optimizer.step()
        
        avg_cost += loss / total_batch
    
    print('[Epoch:{}] cost = {}'.format(epoch + 1, avg_cost))

[Epoch:1] cost = 0.6648455262184143
[Epoch:2] cost = 0.6214804649353027
[Epoch:3] cost = 0.6080071330070496
[Epoch:4] cost = 0.5750889182090759
[Epoch:5] cost = 0.5297144055366516
[Epoch:6] cost = 0.45980486273765564
[Epoch:7] cost = 0.36359527707099915
[Epoch:8] cost = 0.29959940910339355
[Epoch:9] cost = 0.2230401337146759
[Epoch:10] cost = 0.13365304470062256
[Epoch:11] cost = 0.06788232922554016
[Epoch:12] cost = 0.041417308151721954
[Epoch:13] cost = 0.03369062766432762
[Epoch:14] cost = 0.017089786008000374
[Epoch:15] cost = 0.014408216811716557
[Epoch:16] cost = 0.018149694427847862
[Epoch:17] cost = 0.02042374201118946
[Epoch:18] cost = 0.012691648676991463
[Epoch:19] cost = 0.01539478451013565
[Epoch:20] cost = 0.015479791909456253


In [74]:
torch.save(net.state_dict(), 'model.pth')

In [75]:
new_net = CNN().to(device)

In [76]:
new_net.load_state_dict(torch.load('model.pth'))

<All keys matched successfully>

In [77]:
print(net.layer1[0])
print(new_net.layer1[0])

print(net.layer1[0].weight[0][0][0])
print(new_net.layer1[0].weight[0][0][0])

net.layer1[0].weight[0] == new_net.layer1[0].weight[0]

Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
tensor([-0.1327, -0.0486, -0.0463, -0.0606,  0.1332], grad_fn=<SelectBackward>)
tensor([-0.1327, -0.0486, -0.0463, -0.0606,  0.1332], grad_fn=<SelectBackward>)


tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

In [78]:
trans = torchvision.transforms.Compose([
    transforms.Resize((64, 128)),
    transforms.ToTensor()
])
test_data = torchvision.datasets.ImageFolder(root='taco_and_burrito/test_resize',
                                            transform=trans)

In [79]:
test_set = DataLoader(dataset=test_data, batch_size=len(test_data))

In [80]:
with torch.no_grad():
    for num, data in enumerate(test_set):
        imgs, label = data
        imgs = imgs.to(device)
        label = label.to(device)
        
        prediction = net(imgs)
        correct_prediction = torch.argmax(prediction, 1) == label
        
        accuracy = correct_prediction.float().mean()
        print('Accuracy:', accuracy.item())

Accuracy: 0.6166666746139526
